<?php if (!defined('BASEPATH')) exit('No direct script access allowed');

class Migration_Create_vw_pekerjaan_kategori extends CI_Migration
{
	public function up()
	{
		$ci =& get_instance();

		$db_config = [];
		$db_file = APPPATH . 'config/database.php';
		if (file_exists($db_file)) {
			include($db_file);
			if (!isset($db['db_sipp']) || empty($db['db_sipp']['hostname'])) {
				return;
			}
		} else {
			return;
		}

		$sipp_db = $ci->load->database('db_sipp', TRUE);

		$sql = "CREATE OR REPLACE VIEW vw_pekerjaan_kategori AS
			SELECT
			    p.id,
			    p.nama        AS nama_pihak,
			    p.pekerjaan   AS pekerjaan_asli,
			    CASE
			      WHEN p.pekerjaan IS NULL OR TRIM(p.pekerjaan) = '' THEN 'Tidak Diisi'

			      WHEN TRIM(p.pekerjaan) REGEXP '^[-.[:space:]]+$'
			        OR TRIM(p.pekerjaan) REGEXP '^[0-9]+$'
			        OR TRIM(p.pekerjaan) REGEXP '^[0-9]{1,2}/[0-9]{1,2}/[0-9]{2,4}$'
			        OR TRIM(p.pekerjaan) REGEXP '^(.)\\\\1{3,}$'
			        OR TRIM(p.pekerjaan) IN ('SD','SMP','SLTA','SLTP','SMA','MTs','Mts','Sarjana','S1','S2','S3','Sph')
			        OR TRIM(p.pekerjaan) IN ('Tiada','Balita','Belum Kawin')
			        OR p.pekerjaan LIKE '%tidak ada%' OR p.pekerjaan LIKE '%tidak diketahui%'
			        OR p.pekerjaan LIKE '%tidak tahu%' OR p.pekerjaan LIKE '%tidak tau%'
			        OR p.pekerjaan LIKE '%kosong%'
			        OR p.pekerjaan LIKE '%nihil%'      OR p.pekerjaan LIKE '%n/a%'
			        OR p.pekerjaan LIKE '%belum sekolah%' OR p.pekerjaan LIKE '%tidak sekolah%'
			        THEN 'Tidak diketahui'

			      WHEN p.pekerjaan LIKE '%tetangga%' OR p.pekerjaan LIKE '%teman%'
			        OR p.pekerjaan LIKE '%saudara%'  OR p.pekerjaan LIKE '%adik%'
			        OR p.pekerjaan LIKE '%kakak%'    OR p.pekerjaan LIKE '%ipar%'
			        OR p.pekerjaan LIKE '%sepupu%'
			        OR p.pekerjaan LIKE '%keponakan%' OR p.pekerjaan LIKE '%paman%'
			        OR p.pekerjaan LIKE '%bibi%'      OR p.pekerjaan LIKE '%kakek%'
			        OR p.pekerjaan LIKE '%nenek%'     OR p.pekerjaan LIKE '%ibu kandung%'
			        OR p.pekerjaan LIKE '%ayah kandung%'
			        OR TRIM(p.pekerjaan) IN ('Perempuan','Laki-laki')
			        THEN 'Bukan Pekerjaan (Isian Tidak Valid)'

			      WHEN (p.pekerjaan LIKE '%kerja%' AND (p.pekerjaan LIKE '%tidak%'
			        OR p.pekerjaan LIKE '%todak%' OR p.pekerjaan LIKE '%ridak%'
			        OR p.pekerjaan LIKE '%belum%' OR p.pekerjaan LIKE '%beum%'
			        OR p.pekerjaan LIKE '%befja%' OR p.pekerjaan LIKE '%bekeerja%'))
			        OR p.pekerjaan LIKE '%pengangguran%'
			        OR TRIM(p.pekerjaan) IN ('Belum','Tidak','Tdk bekerja')
			        THEN 'Belum/tidak bekerja'

			      WHEN p.pekerjaan LIKE '%guru%' OR p.pekerjaan REGEXP 'g[[:space:]]*u[[:space:]]*r[[:space:]]*u'
			        OR p.pekerjaan LIKE '%pengajar%' OR p.pekerjaan LIKE '%mengajar%'
			        OR p.pekerjaan LIKE '%kepala sekolah%'
			        OR p.pekerjaan LIKE '%tentor%' OR p.pekerjaan LIKE '%les privat%'
			        OR p.pekerjaan LIKE '%tenaga kependidikan%' OR p.pekerjaan LIKE '%tenaga pendidik%'
			        OR p.pekerjaan LIKE '%pembina pramuka%'
			        OR p.pekerjaan LIKE '%masih sekolah%'
			        THEN 'Guru'
			      WHEN p.pekerjaan LIKE '%dosen%' OR p.pekerjaan LIKE '%akademisi%'
			        THEN 'Dosen'
			      WHEN p.pekerjaan LIKE '%dokter%'                                              THEN 'Dokter'
			      WHEN p.pekerjaan LIKE '%bidan%'                                               THEN 'Bidan'
			      WHEN p.pekerjaan LIKE '%perawat%' OR p.pekerjaan LIKE '%tenaga kesehatan%'
			        OR p.pekerjaan LIKE '%analis kesehatan%' OR p.pekerjaan LIKE '%analisis kesehatan%'
			        OR p.pekerjaan LIKE '%analis medis%' OR p.pekerjaan LIKE '%analis laboratorium%'
			        OR p.pekerjaan LIKE '%laboratorium%'
			        OR p.pekerjaan LIKE '%rumah sakit%' OR p.pekerjaan LIKE '%rsud%'
			        OR p.pekerjaan LIKE '%puskesmas%'   OR p.pekerjaan LIKE '%klinik%'
			        OR p.pekerjaan LIKE '%radiografer%' OR p.pekerjaan LIKE '%radio grafer%'
			        OR p.pekerjaan LIKE '%gizi%'
			        OR p.pekerjaan LIKE '%petugas medis%'
			        THEN 'Perawat'
			      WHEN p.pekerjaan LIKE '%apoteker%' OR p.pekerjaan LIKE '%farmasi%'
			        OR p.pekerjaan LIKE '%apotek%'
			        THEN 'Apoteker'
			      WHEN p.pekerjaan LIKE '%psikolog%' OR p.pekerjaan LIKE '%psikiater%'          THEN 'Psikiater/psikolog'
			      WHEN p.pekerjaan LIKE '%notaris%'                                             THEN 'Notaris'
			      WHEN p.pekerjaan LIKE '%akuntan%'
			        OR p.pekerjaan LIKE '%finance%' OR p.pekerjaan LIKE '%accounting%'
			        OR p.pekerjaan LIKE '%akunting%' OR p.pekerjaan LIKE '%bendahara%'
			        OR p.pekerjaan LIKE '%bagian keuangan%'
			        THEN 'Akuntan'
			      WHEN p.pekerjaan LIKE '%arsitek%' OR p.pekerjaan LIKE '%arseitek%'
			        THEN 'Arsitek'
			      WHEN p.pekerjaan LIKE '%pengacara%' OR p.pekerjaan LIKE '%advokat%'
			        OR p.pekerjaan LIKE '%advokad%'   OR p.pekerjaan LIKE '%advocat%'
			        OR p.pekerjaan LIKE '%pengcara%'
			        OR p.pekerjaan LIKE '%penasehat hukum%' OR p.pekerjaan LIKE '%bantuan hukum%'
			        OR p.pekerjaan LIKE '%paralegal%'
			        THEN 'Pengacara'
			      WHEN p.pekerjaan LIKE '%wartawan%' OR p.pekerjaan LIKE '%jurnalis%'
			        OR p.pekerjaan LIKE '%penulis%'
			        OR p.pekerjaan LIKE '%pers %' OR p.pekerjaan LIKE '%kwri%'
			        THEN 'Wartawan'
			      WHEN p.pekerjaan LIKE '%konsultan%' OR p.pekerjaan LIKE '%consultant%'
			        THEN 'Konsultan'
			      WHEN p.pekerjaan LIKE '%makelar%'
			        OR p.pekerjaan LIKE '%agen properti%' OR p.pekerjaan LIKE '%agent property%'
			        OR p.pekerjaan LIKE '%property%' OR p.pekerjaan LIKE '%properti%'
			        THEN 'Pialang'
			      WHEN p.pekerjaan LIKE '%pilot%'                                               THEN 'Pilot'
			      WHEN p.pekerjaan LIKE '%penyiar radio%'                                       THEN 'Penyiar radio'
			      WHEN p.pekerjaan LIKE '%penyanyi%' OR p.pekerjaan LIKE '%musisi%' OR p.pekerjaan LIKE '%musik%'
			        OR p.pekerjaan LIKE '%seniman%' OR p.pekerjaan LIKE '%pengamen%' OR p.pekerjaan LIKE '%pekerja seni%'
			        OR p.pekerjaan LIKE '%fotografer%'
			        OR p.pekerjaan LIKE '%sinden%' OR p.pekerjaan LIKE '%dalang%'
			        OR p.pekerjaan LIKE '%pengiring orkes%' OR p.pekerjaan LIKE '%senima%'
			        OR p.pekerjaan LIKE '%pelukis%' OR p.pekerjaan LIKE '%ilustrator%'
			        THEN 'Seniman'
			      WHEN p.pekerjaan LIKE '%imam masjid%'
			        OR p.pekerjaan LIKE '%marbot%' OR p.pekerjaan LIKE '%takmir%'
			        OR p.pekerjaan LIKE '%ustadz%' OR p.pekerjaan LIKE '%ustadzah%'
			        OR p.pekerjaan LIKE '%mubaligh%' OR p.pekerjaan LIKE '%muballigh%'
			        OR p.pekerjaan LIKE '%kyai%' OR p.pekerjaan LIKE '%penceramah%'
			        OR p.pekerjaan LIKE '%penyuluh agama%'
			        THEN 'Imam masjid'
			      WHEN p.pekerjaan LIKE '%pendeta%'                                             THEN 'Pendeta'
			      WHEN p.pekerjaan LIKE '%pastur%' OR p.pekerjaan LIKE '%pastor%'               THEN 'Pastur'
			      WHEN p.pekerjaan LIKE '%biarawati%'                                           THEN 'Biarawati'
			      WHEN p.pekerjaan LIKE '%bupati%'                                              THEN 'Bupati'
			      WHEN p.pekerjaan LIKE '%walikota%' OR p.pekerjaan LIKE '%wali kota%'          THEN 'Walikota'
			      WHEN p.pekerjaan LIKE '%gubernur%'                                            THEN 'Gubernur'
			      WHEN p.pekerjaan LIKE '%camat%'                                               THEN 'Camat'
			      WHEN p.pekerjaan LIKE '%menteri%' OR p.pekerjaan LIKE '%kabinet%'             THEN 'Anggota Kabinet /Kementerian'
			      WHEN p.pekerjaan LIKE '%duta besar%' OR p.pekerjaan LIKE '%kedutaan%'
			        OR p.pekerjaan LIKE '%kedubes%'
			        THEN 'Duta Besar'
			      WHEN p.pekerjaan LIKE '%anggota dpd%'
			        OR p.pekerjaan LIKE '%dprd%'
			        OR p.pekerjaan LIKE '%anggota dpr%'
			        OR p.pekerjaan LIKE '%anggota dewan%'
			        THEN 'Anggota DPD'
			      WHEN p.pekerjaan LIKE '%anggota bpk%'
			        OR p.pekerjaan LIKE '%bawaslu%' OR p.pekerjaan LIKE '%komisioner%'
			        THEN 'Anggota BPK'
			      WHEN p.pekerjaan LIKE '%mahkamah konstitusi%'                                 THEN 'Anggota Mahkamah Konstitusi'
			      WHEN p.pekerjaan LIKE '%hakim%' OR p.pekerjaan LIKE '%jaksa%'
			        THEN 'Pegawai Negeri Sipil'
			      WHEN p.pekerjaan LIKE '%sopir%' OR p.pekerjaan LIKE '%supir%'
			        OR p.pekerjaan LIKE '%driver%' OR p.pekerjaan LIKE '%ojek%'
			        OR p.pekerjaan LIKE '%pengemudi%' OR p.pekerjaan LIKE '%kurir%'
			        OR p.pekerjaan LIKE '%kernet%' OR p.pekerjaan LIKE '%kenet%'
			        OR p.pekerjaan LIKE '%antar jemput%'
			        OR p.pekerjaan LIKE '%go-jek%' OR p.pekerjaan LIKE '%gojek%'
			        OR p.pekerjaan LIKE '%grab%' OR p.pekerjaan LIKE '%taxi%'
			        OR p.pekerjaan LIKE '%becak%' OR p.pekerjaan LIKE '%tambangan%'
			        OR p.pekerjaan LIKE '%porter%' OR p.pekerjaan LIKE '%bandara%'
			        OR p.pekerjaan LIKE '%kurier%'
			        THEN 'Sopir'
			      WHEN p.pekerjaan LIKE '%transportasi%' OR p.pekerjaan LIKE '%travel%'
			        OR p.pekerjaan LIKE '%expedisi%' OR p.pekerjaan LIKE '%ekpedisi%'
			        THEN 'Transportasi'
			      WHEN p.pekerjaan LIKE '%nelayan%' OR p.pekerjaan LIKE '%perikanan%'
			        THEN 'Nelayan/perikanan'
			      WHEN p.pekerjaan LIKE '%peternak%' OR p.pekerjaan LIKE '%ternak%'
			        OR p.pekerjaan LIKE '%pertenak%'
			        OR p.pekerjaan LIKE '%tambak%' OR p.pekerjaan LIKE '%petambak%'
			        THEN 'Peternak'
			      WHEN p.pekerjaan LIKE '%petani%' OR p.pekerjaan LIKE '%tani%'
			        OR p.pekerjaan LIKE '%kebun%' OR p.pekerjaan LIKE '%petan%'
			        THEN 'Petani/pekebun'
			      WHEN p.pekerjaan LIKE '%pelaut%' OR p.pekerjaan LIKE '%pelayaran%'
			        OR p.pekerjaan LIKE '%pelayar%'
			        OR p.pekerjaan LIKE '%abk%' OR p.pekerjaan LIKE '%anak buah kapal%'
			        THEN 'Pelaut'
			      WHEN p.pekerjaan LIKE '%buruh%' OR p.pekerjaan LIKE '%kuli%'
			        OR p.pekerjaan LIKE '%harian lepas%'                                        THEN 'Buruh harian lepas'
			      WHEN p.pekerjaan LIKE '%serabutan%' OR p.pekerjaan LIKE '%srabutan%'
			        OR p.pekerjaan LIKE '%searabutan%' OR p.pekerjaan LIKE '%searabutab%'
			        OR p.pekerjaan LIKE '%surabutan%' OR p.pekerjaan LIKE '%serabautan%'
			        OR p.pekerjaan LIKE '%serabuta%'
			        OR p.pekerjaan LIKE '%pencari barang%' OR p.pekerjaan LIKE '%kondektur%'
			        OR p.pekerjaan LIKE '%pemulung%'
			        OR p.pekerjaan LIKE '%pengepul%' OR p.pekerjaan LIKE '%rongsok%'
			        OR p.pekerjaan LIKE '%rosok%'    OR p.pekerjaan LIKE '%barang bekas%'
			        OR p.pekerjaan LIKE '%besi tua%' OR p.pekerjaan LIKE '%manol%'
			        OR p.pekerjaan LIKE '%supeltas%' OR p.pekerjaan LIKE '%penyebrang%'
			        OR p.pekerjaan LIKE '%pencari cacing%' OR p.pekerjaan LIKE '%mencari cacing%'
			        OR p.pekerjaan LIKE '%pekerja kontrak%'
			        THEN 'Pekerja Serabutan / Tidak Tetap'
			      WHEN p.pekerjaan LIKE '%tni%' OR p.pekerjaan LIKE '%tentara%'                 THEN 'Tentara Nasional Indonesia'
			      WHEN p.pekerjaan LIKE '%polri%' OR p.pekerjaan LIKE '%polisi%' OR p.pekerjaan LIKE '%polwan%' THEN 'Kepolisian RI'
			      WHEN p.pekerjaan LIKE '%pns%' OR p.pekerjaan LIKE '%asn%'  OR p.pekerjaan LIKE '%pemadam%'
			        OR p.pekerjaan LIKE '%pegawai negeri%' OR p.pekerjaan LIKE '%aparatur sipil negara%'
			        OR p.pekerjaan LIKE '%aparat sipil negara%' OR p.pekerjaan LIKE '%aparatus sipil negara%'
			        OR p.pekerjaan LIKE '%pegawe negeri%'
			        OR p.pekerjaan LIKE '%pppk%' OR p.pekerjaan LIKE '%p3k%'
			        OR p.pekerjaan LIKE '%ppnpn%'
			        OR p.pekerjaan LIKE '%satpol pp%'
			        OR p.pekerjaan LIKE '%dishub%'   OR p.pekerjaan LIKE '%bkkbn%'
			        OR p.pekerjaan LIKE '%pemkot%'   OR p.pekerjaan LIKE '%pemkab%'
			        OR p.pekerjaan LIKE '%bina marga%' OR p.pekerjaan LIKE '%dinas pekerjaan umum%'
			        OR p.pekerjaan LIKE '%dinas lhk%' OR p.pekerjaan LIKE '%dinas sosial%'
			        THEN 'Pegawai Negeri Sipil'
			      WHEN p.pekerjaan LIKE '%pensiun%' OR p.pekerjaan LIKE '%purnawirawan%'
			        OR p.pekerjaan LIKE '%pesiunan%' OR p.pekerjaan LIKE '%purnakarya%'
			        OR p.pekerjaan LIKE '%pensinan%' OR p.pekerjaan LIKE '%pinsiunan%'
			        OR p.pekerjaan LIKE '%pensunan%' OR p.pekerjaan LIKE '%purnawiran%'
			        OR p.pekerjaan LIKE '%purnawan%' OR p.pekerjaan LIKE '%purna tugas%'
			        OR p.pekerjaan LIKE '%purna dinkes%' OR p.pekerjaan LIKE '%purna bpn%'
			        OR p.pekerjaan LIKE '%pens pemda%'
			        THEN 'Pensiun'
			      WHEN p.pekerjaan LIKE '%pelajar%' OR p.pekerjaan LIKE '%mahasiswa%'
			        OR p.pekerjaan LIKE '%mahasiswi%' OR p.pekerjaan LIKE '%siswa%'
			        OR p.pekerjaan LIKE '%masih sekolah%'
			        THEN 'Pelajar/Mahasiswa'
			      WHEN p.pekerjaan = 'art' OR p.pekerjaan LIKE '%baby sit%' OR p.pekerjaan LIKE '%baby sis%'
			        OR p.pekerjaan LIKE '%babysitter%' OR p.pekerjaan LIKE '%asisten rumah%'
			        OR p.pekerjaan LIKE '%asisten rumahtangga%'
			        OR p.pekerjaan LIKE '%pembantu%' OR p.pekerjaan LIKE '%pengasuh%'           THEN 'Pembantu rumah tangga'
			      WHEN p.pekerjaan LIKE '%rumah tangga%' OR p.pekerjaan REGEXP 'rumah[[:space:]]*ta[n]+g+a'
			        OR p.pekerjaan LIKE '%irt%' OR p.pekerjaan LIKE '%ibu rt%' OR p.pekerjaan LIKE '%ibu rum%'
			        OR p.pekerjaan LIKE '%mengurus%'
			        OR p.pekerjaan LIKE '%ruamh tangga%' OR p.pekerjaan LIKE '%ruah tangga%'
			        OR p.pekerjaan LIKE '%runah tangga%' OR p.pekerjaan LIKE '%tumah tangga%'
			        OR p.pekerjaan LIKE '%homemaker%'
			        THEN 'Mengurus rumah tangga'
			      WHEN p.pekerjaan LIKE '%kesra%' OR p.pekerjaan LIKE '%mudin%'
			        OR p.pekerjaan LIKE '%modin%' OR p.pekerjaan LIKE '%kepala dusun%'
			        OR p.pekerjaan LIKE '%kasun%' OR p.pekerjaan LIKE '%sekretaris desa%'
			        OR p.pekerjaan LIKE '%ketua rt%' OR p.pekerjaan LIKE '%ketua rw%'
			        OR p.pekerjaan LIKE '%perangkat desa%' OR p.pekerjaan LIKE '%kepala desa%'
			        OR p.pekerjaan LIKE '%perangkat%'
			        OR p.pekerjaan LIKE '%prangkat%'  OR p.pekerjaan LIKE '%perangka desa%'
			        OR p.pekerjaan LIKE '%perankat%'  OR p.pekerjaan LIKE '%peranygkat%'
			        OR p.pekerjaan LIKE '%pamong%'    OR p.pekerjaan LIKE '%carik%'
			        OR p.pekerjaan LIKE '%sekdes%'    OR p.pekerjaan LIKE '%sekertaris desa%'
			        OR p.pekerjaan LIKE '%mantan lurah%' OR p.pekerjaan LIKE '%mantan kep. desa%'
			        OR p.pekerjaan LIKE '%aparat desa%'
			        OR p.pekerjaan LIKE '%pendamping desa%'
			        OR p.pekerjaan LIKE '%badan permusyawaratan%'
			        OR p.pekerjaan LIKE '%ka.sun%'
			        THEN 'Perangkat Desa'
			      WHEN p.pekerjaan LIKE '%direktur%' OR p.pekerjaan LIKE '%pemilik%'
			        OR p.pekerjaan LIKE '%owner%'    OR p.pekerjaan LIKE '%kontraktor%'
			        OR p.pekerjaan LIKE '%pemborong%' OR p.pekerjaan LIKE '%rental%'
			        OR p.pekerjaan LIKE '%persewaan%' OR p.pekerjaan LIKE '%penyewaan%'
			        OR p.pekerjaan LIKE '%penyewa mobil%'
			        OR p.pekerjaan LIKE '%ud.%'      OR p.pekerjaan LIKE '% ud %'
			        OR p.pekerjaan LIKE '%kontrak tor%'
			        THEN 'Wiraswasta'
			      WHEN p.pekerjaan LIKE '%bangunan%' OR p.pekerjaan LIKE '%konstruksi%'
			        OR p.pekerjaan LIKE '%kontruksi%' OR p.pekerjaan LIKE '%proyek%'
			        OR p.pekerjaan LIKE '%instalasi listrik%' OR p.pekerjaan LIKE '%istalasi%'
			        OR p.pekerjaan LIKE '%bor sumur%' OR p.pekerjaan LIKE '%pengeboran%'
			        OR p.pekerjaan LIKE '%alat berat%' OR p.pekerjaan LIKE '%dozer%'
			        OR p.pekerjaan LIKE '%mandor%'
			        OR p.pekerjaan LIKE '%sound system%' OR p.pekerjaan LIKE '%sound sistem%'
			        THEN 'Konstruksi'
			      WHEN p.pekerjaan LIKE '%jahit%'                                               THEN 'Tukang jahit'
			      WHEN p.pekerjaan LIKE '%tukang las%' OR p.pekerjaan LIKE '%pandai besi%'
			        OR p.pekerjaan LIKE '%pande besi%'
			        THEN 'Tukang las/pandai besi'
			      WHEN p.pekerjaan LIKE '%tukang listrik%'
			        OR p.pekerjaan LIKE '%instalatir%' OR p.pekerjaan LIKE '%pasang listrik%'
			        THEN 'Tukang listrik'
			      WHEN p.pekerjaan LIKE '%montir%' OR p.pekerjaan LIKE '%tambal ban%'
			        OR p.pekerjaan LIKE '%tembel ban%'
			        OR p.pekerjaan LIKE '%servis elektronik%' OR p.pekerjaan LIKE '%service elektronik%'
			        OR p.pekerjaan LIKE '%service%' OR p.pekerjaan LIKE '%servis%'
			        OR p.pekerjaan LIKE '%sevis%'    OR p.pekerjaan REGEXP 'bengkel'
			        OR p.pekerjaan LIKE '%reparasi%' OR p.pekerjaan LIKE '%bengkel%'
			        THEN 'Mekanik'
			      WHEN p.pekerjaan LIKE '%rias%' OR p.pekerjaan LIKE '%salon%'
			        OR p.pekerjaan LIKE '%penata rambut%' OR p.pekerjaan LIKE '%potong rambut%'
			        OR p.pekerjaan LIKE '%pangkas rambut%'
			        OR p.pekerjaan LIKE '%make up%'  OR p.pekerjaan LIKE '%mua %'
			        OR p.pekerjaan LIKE '%beautician%' OR p.pekerjaan LIKE '%beauty%'
			        THEN 'Penata rias'
			      WHEN p.pekerjaan LIKE '%koki%' OR p.pekerjaan LIKE '%juru masak%'
			        OR p.pekerjaan LIKE '%barista%'
			        OR p.pekerjaan LIKE '%kitchen%' OR p.pekerjaan LIKE '%resto%'
			        OR p.pekerjaan LIKE '%rumah makan%' OR p.pekerjaan LIKE '%kantin%'
			        THEN 'Juru masak'
			      WHEN p.pekerjaan LIKE '%parkir%' OR p.pekerjaan LIKE '%jukir%'
			        THEN 'Juru Parkir'
			      WHEN p.pekerjaan LIKE '%mebel%' OR p.pekerjaan LIKE '%meubel%'
			        OR p.pekerjaan LIKE '%pengrajin%' OR p.pekerjaan LIKE '%pengerajin%'        THEN 'Pengrajin'
			      WHEN p.pekerjaan LIKE '%perdagangan%' OR p.pekerjaan LIKE '%perdang%'
			        OR p.pekerjaan REGEXP 'perda[a-z]*ng[a-z]*n'
			        OR p.pekerjaan LIKE '%distributor%' OR p.pekerjaan LIKE '%distributir%'
			        OR p.pekerjaan LIKE '%grosir%'
			        OR p.pekerjaan LIKE '%ekspor%' OR p.pekerjaan LIKE '%impor%' OR p.pekerjaan LIKE '%importir%'
			        OR p.pekerjaan LIKE '%suplier%' OR p.pekerjaan LIKE '%supplier%' OR p.pekerjaan LIKE '%supliyer%'
			        OR p.pekerjaan LIKE '%vendor%'
			        OR p.pekerjaan LIKE '%dealer%' OR p.pekerjaan LIKE '%deller%'
			        OR p.pekerjaan LIKE '%showroom%' OR p.pekerjaan LIKE '%sorum%'
			        THEN 'Perdagangan'
			      WHEN p.pekerjaan LIKE '%pabrik%' OR p.pekerjaan LIKE '%industri%'
			        OR p.pekerjaan LIKE '%manufaktur%' OR p.pekerjaan LIKE '%produksi%'
			        OR p.pekerjaan LIKE '%produsen%'
			        THEN 'Industri'
			      WHEN p.pekerjaan LIKE '%wiraswasta%' OR p.pekerjaan LIKE '%wirausaha%'
			        OR p.pekerjaan LIKE '%wirausahawan%' OR p.pekerjaan LIKE '%umkm%'
			        OR p.pekerjaan LIKE '%dagang%' OR p.pekerjaan LIKE '%jualan%'
			        OR p.pekerjaan LIKE '%jual%'  OR p.pekerjaan LIKE '%usaha%'
			        OR p.pekerjaan LIKE '%toko%'  OR p.pekerjaan LIKE '%warung%'
			        OR p.pekerjaan LIKE '%warkop%' OR p.pekerjaan LIKE '%waruang kopi%'
			        OR p.pekerjaan LIKE '%pedang%'
			        OR p.pekerjaan LIKE '%home industri%' OR p.pekerjaan LIKE '%online%'
			        OR p.pekerjaan LIKE '%biro jasa%' OR p.pekerjaan LIKE '%ekspedisi%'
			        OR p.pekerjaan LIKE '%percetakan%' OR p.pekerjaan LIKE '%konveksi%'
			        OR p.pekerjaan LIKE '%konpeksi%'
			        OR p.pekerjaan LIKE '%catering%'
			        OR p.pekerjaan LIKE '%laundry%'   OR p.pekerjaan LIKE '%loundry%'
			        OR p.pekerjaan LIKE '%mracang%'   OR p.pekerjaan LIKE '%meracang%'
			        OR p.pekerjaan LIKE '%pertamini%'
			        OR p.pekerjaan LIKE '%agen es%'
			        OR p.pekerjaan LIKE '%agen krupuk%' OR p.pekerjaan LIKE '%agen koran%'
			        OR p.pekerjaan LIKE '%konter%'
			        OR p.pekerjaan LIKE '%agang%'
			        OR p.pekerjaan REGEXP 'wira[a-z]*ta'                                        THEN 'Pedagang'
			      WHEN p.pekerjaan LIKE '%pln%' OR p.pekerjaan LIKE '%jasa marga%'
			        OR p.pekerjaan LIKE '%angkasa pura%' OR p.pekerjaan LIKE '%pelabuhan indonesia%'
			        OR p.pekerjaan LIKE '%pelindo%' OR p.pekerjaan LIKE '%telkom%'
			        OR p.pekerjaan LIKE '%pdam%'
			        THEN 'Karyawan BUMN'
			      WHEN p.pekerjaan LIKE '%bumn%'                                                THEN 'Karyawan BUMN'
			      WHEN p.pekerjaan LIKE '%bumd%'                                                THEN 'Karyawan BUMD'
			      WHEN p.pekerjaan LIKE '%honorer%' OR p.pekerjaan LIKE '%honore %'
			        THEN 'Karyawan Honorer'
			      WHEN p.pekerjaan LIKE '%tki%' OR p.pekerjaan LIKE '%tkw%'
			        OR p.pekerjaan LIKE '%tenaga kerja wanita%' OR p.pekerjaan LIKE '%tenaga kerja indonesia%'
			        OR p.pekerjaan LIKE '%pekerja migran%'                                      THEN 'TKI/TKW (Pekerja Migran)'
			      WHEN p.pekerjaan LIKE '%freelance%' OR p.pekerjaan LIKE '%freelancer%'
			        OR p.pekerjaan LIKE '%desainer%' OR p.pekerjaan LIKE '%designer%'
			        OR p.pekerjaan LIKE '%freeland%' OR p.pekerjaan LIKE '%free land%'
			        OR p.pekerjaan LIKE '%freelence%' OR p.pekerjaan LIKE '%fleelancer%'
			        OR p.pekerjaan LIKE '%free line%' OR p.pekerjaan LIKE '%freeline%'
			        OR p.pekerjaan LIKE '%instruktur%' OR p.pekerjaan LIKE '%terapis%'
			        OR p.pekerjaan LIKE '%teraphis%' OR p.pekerjaan LIKE '%therapies%'
			        OR p.pekerjaan LIKE '%terapi%'    OR p.pekerjaan LIKE '%tabib%'
			        OR p.pekerjaan LIKE '%paranormal%' OR p.pekerjaan LIKE '%dukun%'
			        OR p.pekerjaan LIKE '%pengobatan alternatif%' OR p.pekerjaan LIKE '%penggobatan%'
			        OR p.pekerjaan LIKE '%konten kreator%' OR p.pekerjaan LIKE '%entertain%'
			        OR p.pekerjaan LIKE '%content creator%' OR p.pekerjaan LIKE '%influencer%'
			        OR p.pekerjaan LIKE '%wedding%'   OR p.pekerjaan LIKE '%event organiz%'
			        OR p.pekerjaan LIKE '%event organis%' OR p.pekerjaan LIKE '%even organizer%'
			        OR p.pekerjaan LIKE '%eo pameran%' OR p.pekerjaan LIKE '%decor%'
			        OR p.pekerjaan LIKE '%kameraman%' OR p.pekerjaan LIKE '%studio foto%'
			        OR p.pekerjaan LIKE '%fotografi%' OR p.pekerjaan LIKE '%drafter%'
			        OR p.pekerjaan LIKE '%dravter%'   OR p.pekerjaan LIKE '%estimator%'
			        OR p.pekerjaan LIKE '%desain%'    OR p.pekerjaan LIKE '%design%'
			        OR p.pekerjaan LIKE '%disagn%'
			        OR p.pekerjaan LIKE '%programer%' OR p.pekerjaan LIKE '%programmer%'
			        OR p.pekerjaan LIKE '%pragraming%'
			        OR p.pekerjaan LIKE '%trader%'    OR p.pekerjaan LIKE '%surveyor%'
			        OR p.pekerjaan LIKE '%pelatih%'   OR p.pekerjaan LIKE '%trainer%'
			        OR p.pekerjaan LIKE '%atlet%'     OR p.pekerjaan LIKE '%pembalap%'
			        OR p.pekerjaan LIKE '%pekerja sosial%'
			        THEN 'Freelance / Pekerja Lepas'
			      WHEN p.pekerjaan LIKE '%karyawan%' OR p.pekerjaan LIKE '%karyawati%' OR p.pekerjaan LIKE '%karaywa%'
			        OR p.pekerjaan LIKE '%kayawan%'  OR p.pekerjaan LIKE '%kayawati%'
			        OR p.pekerjaan LIKE '%karyaw%'
			        OR p.pekerjaan LIKE '%pegawai%'  OR p.pekerjaan LIKE '%swast%' OR p.pekerjaan LIKE '%swst%'
			        OR p.pekerjaan LIKE '%swsata%'   OR p.pekerjaan LIKE '%sewasta%'
			        OR p.pekerjaan LIKE '%swaata%'   OR p.pekerjaan LIKE '%admin%'
			        OR p.pekerjaan LIKE '%swasa%'    OR p.pekerjaan LIKE '%swaswa%'
			        OR p.pekerjaan LIKE '%sawsta%'   OR p.pekerjaan LIKE '%swqasta%'
			        OR p.pekerjaan LIKE '%suwasta%'  OR p.pekerjaan LIKE '%swaasta%'
			        OR p.pekerjaan LIKE '%dwasta%'   OR p.pekerjaan LIKE '%swata%'
			        OR TRIM(p.pekerjaan) = 'SWA'
			        OR p.pekerjaan LIKE '%staff%'    OR p.pekerjaan LIKE '%staf%'
			        OR p.pekerjaan LIKE '%sales%'    OR p.pekerjaan LIKE '%marketing%'
			        OR p.pekerjaan LIKE '%spg%'      OR p.pekerjaan LIKE '%penjaga%'
			        OR p.pekerjaan LIKE '%jaga villa%' OR p.pekerjaan LIKE '%jaga stan%'
			        OR p.pekerjaan LIKE '%jaga stand%'
			        OR p.pekerjaan LIKE '%cleaning%' OR p.pekerjaan LIKE '%clening%'
			        OR p.pekerjaan LIKE '%cleanning%' OR p.pekerjaan LIKE '%klining%'
			        OR p.pekerjaan LIKE '%kebersihan%' OR p.pekerjaan LIKE '%teknisi%'
			        OR p.pekerjaan LIKE '%tekhnisi%'
			        OR p.pekerjaan LIKE '%operator%' OR p.pekerjaan LIKE '%kasir%'
			        OR p.pekerjaan LIKE '%satpam%'   OR p.pekerjaan LIKE '%security%'
			        OR p.pekerjaan LIKE '%scurity%'  OR p.pekerjaan LIKE '%sekuriti%'
			        OR p.pekerjaan REGEXP 'sec?ur[i]?t[iy]'
			        OR p.pekerjaan LIKE '%pramuniaga%' OR p.pekerjaan LIKE '%office boy%'
			        OR p.pekerjaan LIKE '%manager%'  OR p.pekerjaan LIKE '%manajer%'
			        OR p.pekerjaan LIKE '%maneger%'
			        OR p.pekerjaan LIKE '%asuransi%'
			        OR p.pekerjaan LIKE '%prudential%' OR p.pekerjaan LIKE '%prudencial%'
			        OR p.pekerjaan LIKE '%pelayan%'  OR p.pekerjaan LIKE '%pramugari%'
			        OR p.pekerjaan LIKE '%waiter%'   OR p.pekerjaan LIKE '%waitres%'
			        OR p.pekerjaan LIKE '%pramusaji%'
			        OR p.pekerjaan LIKE '%front desk%' OR p.pekerjaan LIKE '%resepsionis%'
			        OR p.pekerjaan LIKE '%supervisor%' OR p.pekerjaan LIKE '%spv%'
			        OR p.pekerjaan LIKE '%hrd%'       OR p.pekerjaan LIKE '%human resource%'
			        OR p.pekerjaan LIKE '%maintenance%' OR p.pekerjaan LIKE '%maintanace%'
			        OR p.pekerjaan LIKE '%engineering%'
			        OR p.pekerjaan LIKE '%kolektor%' OR p.pekerjaan LIKE '%kolector%'
			        OR p.pekerjaan LIKE '%collector%'
			        OR p.pekerjaan LIKE 'pt %' OR p.pekerjaan LIKE '% pt %' OR p.pekerjaan LIKE '%pt.%'
			        OR p.pekerjaan LIKE '%cv.%'      OR p.pekerjaan LIKE '% cv %'               THEN 'Karyawan swasta'
			      WHEN p.pekerjaan LIKE '%mekanik%' OR p.pekerjaan LIKE '%bengkel%'             THEN 'Mekanik'
			      WHEN p.pekerjaan LIKE '%tukang%' OR p.pekerjaan LIKE '%pertukangan%'          THEN 'Tukang / Pekerja Terampil Lainnya'
			      WHEN TRIM(p.pekerjaan) = 'Lainnya' OR p.pekerjaan LIKE '%pekerjaan lain%'
			        OR TRIM(p.pekerjaan) = 'Lain-lain' OR TRIM(p.pekerjaan) = 'Other'
			        THEN 'Lainnya'
			      ELSE 'Lainnya / Tidak Teridentifikasi'
			    END AS kategori
			FROM pihak p";

		$sipp_db->query($sql);
	}

	public function down()
	{
		// $ci =& get_instance();

		// $db_config = [];
		// $db_file = APPPATH . 'config/database.php';
		// if (file_exists($db_file)) {
		// 	include($db_file);
		// 	if (!isset($db['db_sipp']) || empty($db['db_sipp']['hostname'])) {
		// 		return;
		// 	}
		// } else {
		// 	return;
		// }

		// $sipp_db = $ci->load->database('db_sipp', TRUE);
		// $sipp_db->query("DROP VIEW IF EXISTS vw_pekerjaan_kategori");
	}
}
